Redesign with bevy : Player behaviours
remiCzn/rust-game pull request #21
Opened 2022-08-12 15:53 UTC by remiCzn

2022-08-13 14:43 UTC, tartule requested changes

2022-08-13 14:43 UTC, tartule commented on src/plugins/player/init.rs
> +            transform: Transform::from_scale(Vec3::splat(3.0)),
Transforms need to be component of the object, in order to handle rescale/ movement if needed
2 transforms needed : 
1. global transform : manage by default (do not need to specify it), and updated in the post_processing step, represent position relative to the reference frame (window)
2. transform : manage the position relative to a parent.

2022-08-13 14:43 UTC, tartule commented on src/plugins/player/init.rs
> +        .insert(PlayerAnimation::new())
Overide pervious transform field set l19. Means that the other component that would render in game world would be children of the player (instead of player&other component be children of the same transform object).

2022-08-13 14:43 UTC, tartule commented on src/plugins/player/mod.rs
> +impl Plugin for PlayerPlugin {
Wrong name : ExplorationPlugin and not PlayerPlugin

2022-08-13 14:43 UTC, tartule commented on src/resources/animation_state.rs
> +}
1. to few lines for a separate file, should be with the relenvent file
2. Enum seems to be two things at the same time : animation related field (with it's name) and player status (with the name of the attribute)

2022-08-13 14:43 UTC, tartule commented on src/plugins/player/animations.rs
> +                    }
l 15-l29 : should be handled by the animation. 
Typo l26 (not sure)
l 21 : code too clever. Use : "let ... = if player_animation=4 {player_animation+1} else {0}

2022-08-13 14:43 UTC, tartule commented on src/plugins/player/init.rs
> +    let texture_atlas = TextureAtlas::from_grid(player_sheet, Vec2::new(19.5, 27.0), 3, 1);
not sure why l11/12 is not used inside the animation. Issue related : Unclear what represent 19.5, 27.0, 3, 1 . (position or parameters needed to load the animation)

2022-08-13 14:43 UTC, tartule commented on src/components/player_animation.rs
> +}
new -> default ?

2022-08-15 07:39 UTC, remiCzn commented on src/components/player_animation.rs
> +}
ok

2022-08-15 07:47 UTC, remiCzn commented on src/plugins/player/animations.rs
> +                    }
1) ok
2) Not, it's a loop, when you check the asset, you want have a loop with 1) move the left foot forward 2) both legs in the middle 3) move the right foot forward 4) both legs in the middle. So, 4th (= `3`) and 2nd (= `1`) sprite are the same
3) not sure I understand what you mean. Is `a = (a+1) % 4` not clear enough for you?

2022-08-15 07:54 UTC, remiCzn commented on src/plugins/player/mod.rs
> +impl Plugin for PlayerPlugin {
No, according to me it is playerplugin in the sense that it will contain all the systems for the player, both in exploration and in combat

2022-08-15 07:57 UTC, remiCzn commented on src/resources/animation_state.rs
> +}
1. ok
2. This enum has meaning only for the animation, it does not contain the state of the player. It is necessary to know if the player is moving (so use "Moving") or not (so use "Idle") to play the animation accordingly. Let's imagine that we add a new animation (let's imagine "Dancing"), we will have to add an element to this enum, but this "state" has no meaning for the player, because the state "Dancing" has no importance in the gameplay.

2022-08-15 09:27 UTC, remiCzn commented on src/components/player_animation.rs
> +impl PlayerAnimation {
I tried to use the native AnimationPlayer of bevy, but I found it not very practical

2022-08-15 09:28 UTC, remiCzn commented on src/main.rs
> +        .add_plugin(PlayerPlugin)
I think it's always better to structure well from the beginning, it will always be better when we move to something of a bigger scale

2022-08-15 09:29 UTC, remiCzn commented on src/plugins/player/init.rs
> +    let texture_atlas = TextureAtlas::from_grid(player_sheet, Vec2::new(19.5, 27.0), 3, 1);
l11/12 are use to build the texture_atlas_handle below

2022-08-15 09:35 UTC, remiCzn commented on src/plugins/player/init.rs
> +            transform: Transform::from_scale(Vec3::splat(3.0)),
At this stage of the redesign, we can consider that everything is placed relative to the window.
A next step will be to create a parent that will act as a camera, and we will then be able to place the player according to his parent
I don't think that's the purpose of this step here

2022-08-15 09:38 UTC, remiCzn commented on src/plugins/player/init.rs
> +        .insert(PlayerAnimation::new())
Why? there is no transform in `PlayerAnimation`

2022-08-15 11:34 UTC, tartule commented on src/components/player_animation.rs
> +impl PlayerAnimation {
PlayerAnimation -> CharacterAnimation

2022-08-15 11:36 UTC, tartule commented on src/main.rs
> +        .add_plugin(PlayerPlugin)
if you want

2022-08-15 11:38 UTC, tartule commented on src/components/player_animation.rs
> +impl PlayerAnimation {
(player in bevvy refer to playing as in when we are in the state play)

2022-08-15 11:42 UTC, tartule commented on src/plugins/player/init.rs
> +    let texture_atlas = TextureAtlas::from_grid(player_sheet, Vec2::new(19.5, 27.0), 3, 1);
insert adds comonent to a entity. Here, why not directly creating the whole animation entity using the PlayerAnimation class

2022-08-15 11:45 UTC, tartule commented on src/plugins/player/mod.rs
> +impl Plugin for PlayerPlugin {
Ok, then it's not wrong, but not explicit/missleading : for the moment, the only implementation with name player are explorationState specific

2022-08-15 11:47 UTC, tartule commented on src/resources/animation_state.rs
> +}
2. Should be mre clear with 1. and the resolving of 1. in animation.rs

2022-08-15 12:11 UTC, tartule commented on src/plugins/player/animations.rs
> +                    }
3. I did that comment because i did not understand it at first read, probabbly personal preferences

2022-08-15 15:47 UTC, tartule approved these changes

2022-08-16 15:38 UTC, tartule approved these changes

2022-08-16 15:47 UTC, merged