Test bevy
remiCzn/rust-game pull request #22
Opened 2022-08-16 21:38 UTC by tartule

2022-08-19 17:24 UTC, remiCzn requested changes

2022-08-19 17:24 UTC, remiCzn commented on src/animation/component.rs
> +    frame_to_sprite_index: Vec<usize>,
```suggestion
    frame_sprite_indexes: Vec<usize>,
```
Found it more clear (idem for the ones in this file and in the other files)

2022-08-19 17:24 UTC, remiCzn commented on src/animation/component.rs
> +    pub fn get_sprite_index(&mut self, time: &Res<Time>) -> usize {
```suggestion
    pub fn forward_animation(&mut self, time: &Res<Time>) -> usize {
```

2022-08-19 17:24 UTC, remiCzn commented on src/animation/init.rs
> +    }
Here, you insert an AnimationBundle in the entity, but don't you remove the old AnimationBundle? (each time you change the animation I mean)

2022-08-19 17:24 UTC, remiCzn commented on src/animation/init.rs
> +        let json_animation: JsonAnimationEncoding = serde_json::from_str(animation_param).unwrap();
Why don't you parse this before receiving it from the event?
I found it's better to separate functionnal code and loading code. It could be for example a good idea to create a "loading resources" module, in which you load this animation parameter from a file (not to do here, but maybe in the future)

2022-08-19 17:24 UTC, remiCzn commented on src/entities/character/init.rs
> +    None,
```suggestion
    Idle,
```
None implies the idea of nothing

2022-08-19 17:24 UTC, remiCzn commented on src/entities/character/init.rs
> +pub enum CurrentAction {
```suggestion
pub enum CharacterAnimation {
```
At least, "Current" is not a good idea, because nothing is defined here

2022-08-19 17:24 UTC, remiCzn commented on src/entities/character/init.rs
> +    let id_camera_bg = commands
Why several camera? is it needed?
I think you need only one camera

2022-08-19 17:24 UTC, remiCzn commented on src/entities/character/init.rs
> +pub fn move_character(
this shouldn't be in the "init" file, it describe player behaviour in the runtime

2022-08-19 17:24 UTC, remiCzn commented on src/input/mod.rs
> +    if !direction_switched {
```suggestion
    if velocity == Vec3::ZERO {
```
and then, delete this direction_switched parameter

2022-08-19 17:24 UTC, remiCzn commented on src/animation/init.rs
> +        let character_sheet = asset_server.load(&json_animation.path);
If it tends to be generic, we should remove the mentions of "character" here
+ I don't understand to what extend it is a "init" file, because `update_animation` is used in the runtime

2022-08-19 20:21 UTC, tartule commented on src/animation/init.rs
> +    }
Delete old one. Actually can raise performances issue (dropping component involve modifying the way the ecs is structured). Can't find any example of bevy used this way.

2022-08-19 20:22 UTC, tartule commented on src/animation/component.rs
> +    frame_to_sprite_index: Vec<usize>,
yes !

2022-08-19 20:28 UTC, tartule commented on src/animation/init.rs
> +        let json_animation: JsonAnimationEncoding = serde_json::from_str(animation_param).unwrap();
reason : leftover from developpement process, good point
Even before creating loading ressource module, move l38. to the player spawning instance (ToDO with serealisation finalisation for animation)  :
- 1 json file for the caracter with Action -> correspounding animation string location
- An other file with the correspounding animations parameters

2022-08-19 20:29 UTC, tartule commented on src/entities/character/init.rs
> +    None,
yes!

2022-08-19 20:31 UTC, tartule commented on src/entities/character/init.rs
> +pub enum CurrentAction {
Replace with CharacterAction because used in mouvement as well as animation

2022-08-19 20:45 UTC, tartule commented on src/entities/character/init.rs
> +    let id_camera_bg = commands
Actually yes, didn't use the layer well.

2022-08-19 20:46 UTC, tartule commented on src/entities/character/init.rs
> +    let id_camera_bg = commands
TODO : replace list of camera id with only 1 camera id

2022-08-19 20:56 UTC, tartule commented on src/input/mod.rs
> +    if !direction_switched {
leftover from previous code, velocity has no meaning in input. I deleted this field.

2022-08-19 20:57 UTC, tartule commented on src/input/mod.rs
> +    if !direction_switched {
Also an issue when pressing 2+ keys at the same time. Not sure how to solve it

2022-08-19 20:58 UTC, tartule commented on src/input/mod.rs
> +    if !direction_switched {
(from a gameplay perspective)

2022-08-19 21:05 UTC, tartule commented on src/animation/component.rs
> +    pub fn get_sprite_index(&mut self, time: &Res<Time>) -> usize {
replaced with get_index_animation to add the animation meaning, forward would imply that frame could not stay cst.

2022-08-19 21:07 UTC, tartule commented on src/animation/init.rs
> +        let character_sheet = asset_server.load(&json_animation.path);
yes

2022-08-19 21:08 UTC, tartule commented on src/animation/init.rs
> +        let character_sheet = asset_server.load(&json_animation.path);
1. Yes
2. infact it's used in both. Also file are not structured

2022-08-19 21:11 UTC, tartule commented on src/animation/init.rs
> +        let character_sheet = asset_server.load(&json_animation.path);
resolving insert issue should fix this one

2022-08-19 21:26 UTC, tartule commented on src/entities/character/init.rs
> +pub fn move_character(
Moved to new file

2022-08-19 21:26 UTC, tartule commented on src/entities/character/init.rs
> +    let id_camera_bg = commands
Ok

2022-08-22 10:57 UTC, remiCzn approved these changes

2022-08-22 11:21 UTC, merged